### ISSUE TITLE
[CommunityRequest] Role management system

### ISSUE THREAD

**Issue by sr229** [awau/Clara#106]
As per request of the Kinmosa Discord, slated and planned for 0.4.0, for backporting to 0.3.4.

Here's what they want, which we can add to mainline Clara

![image](https://user-images.githubusercontent.com/14976516/30760623-78a16e5e-a00d-11e7-8e86-8086b36fa369.png)

Basically bootleg Dyno role management system but with more emasculation.

**Comment by sr229** [comment]
@Ovyerus kindly sprint this btw

**Comment by DiscoPangolin** [comment]
yes

**Comment by sr229** [comment]
Sprinted to 0.4.0

**Comment by sr229** [comment]
you're still assigned @Ovyerus tho

**Comment by Ovyerus** [comment]
🏃

**Comment by Ovyerus** [comment]
Done in 1ad1fa4
