### ISSUE TITLE
Revert music dep to ytdl instead of ytdl-node

### ISSUE THREAD

**Issue by sr229** [awau/Clara#118]
@noud02  previously mentioned that we there is a workaround for the ``stdoutmaxBuffer Reached`` error, we can use that again. We would need some more test cases about this tho since 0.2.x has alot of issues with ytdl

**Comment by Ovyerus** [comment]
Isn't it better to use a native module than an external bin?

**Comment by sr229** [comment]
ytdl provides us more easier extensibility compared to the natove one so I say we should give it another go

**Comment by Ovyerus** [comment]
We literally use it for just the one thing in its name.

**Comment by sr229** [comment]
I'll download you

**Comment by Ovyerus** [comment]
Nice
