### ISSUE TITLE
Music should clear queue when crashed

### ISSUE THREAD

**Issue by sr229** [awau/Clara#129]
Apparently queue isn't cleared when the bot suffers a crash

**Comment by Ovyerus** [comment]
What do you mean by this

**Comment by sr229** [comment]
@Ovyerus bot suffering from a crash while a music session is in progress will retain the queue

**Comment by Ovyerus** [comment]
But if the bot crashes, won't everything go down with it?

**Comment by sr229** [comment]
I don't know, it seems to retain it after leaving instantly

**Comment by Ovyerus** [comment]
I guess I'll take a look.

**Comment by Ovyerus** [comment]
Just for clarification, is this referring to a complete bot crash, or just a crash within the music module itself?

**Comment by sr229** [comment]
Only happens rarely now, marking fixed.
