### ISSUE TITLE
Music Architechtural changes

### ISSUE THREAD

**Issue by sr229** [awau/Clara#142]
the Music system should be overhauled for this minor milestone for now, as a quick remedy for some known issues in the current system

- [x] YouTube queues should be saved into a file to mitigate the stream drops we're experiencing with previous implementations
- [x] Precache queued songs before playing to prevent sudden stream drops. Have a file watcher to examine the cache folder.

**Comment by Ovyerus** [comment]
All current streams (except for Twitch) are now saved to a temp file since `b2211b8`.

Todo: Pre-cache the song directly next in queue for speedy play.

**Comment by sr229** [comment]
@Ovyerus I don't think we're chaching YouTube as we are experiencing stream drops

**Comment by sr229** [comment]
Confirmed YT does cache but the handler makes it crash.

**Comment by sr229** [comment]
Confirmed fixed because of Library change, Preloading needs to be reimplemented due to library change

**Comment by Ovyerus** [comment]
Pre-loading of the first item in queues has been added in 6782370, closing.
