### ISSUE TITLE
Double mentions break in ship

### ISSUE THREAD

**Issue by sr229** [awau/Clara#144]
![image](https://user-images.githubusercontent.com/14976516/34412935-2e564428-ec1b-11e7-998c-ff5e036475cd.png)

seems both arg checkers break on spaced nicks/usernames

**Comment by Ovyerus** [comment]
Issue was misinterpreted. Actually happens with any two pairs of mentions.

Fixed in cf3f88e.

**Comment by sr229** [comment]
Issue persistent, reopened.

**Comment by Ovyerus** [comment]
Fixed in 6da4f9d.
