### ISSUE TITLE
Owner/Bot Admin commands

### ISSUE THREAD

**Issue by Ovyerus** [awau/Clara#22]
TODO: Various commands for the bot owner and admins.

- [x] Dynamic command load and unloadncommands, and maybe a JSON file to keep track of unloaded commands to make the command loader skip them.

- [x] Blacklist commands

- [x] Commands to add/remove admins.

- [x] Commands to add/remove alternative prefixes.

**Comment by sr229** [comment]
mfw this never happened (except for prefixes)

**Comment by Ovyerus** [comment]
Music got me sidetracked, and I may need to modify the command loader for dynamic command loading.

**Comment by sr229** [comment]
Backlogged
