### ISSUE TITLE
Greet system

### ISSUE THREAD

**Issue by sr229** [awau/Clara#29]
this is a voluntary job, please assign yourself if you want to work with it

### TODO : 
- [x] A Greet Disable/Enable which is unique for each server (yes, this is not a global command and more guild-specific)

- [x] add a way to automatically detect (and disable the greet system) on Discord Developers' Servers (Discord API, Discord Bots and Discord Developers)

you can whitelist a bot collection server too if you wish.

**Comment by Ovyerus** [comment]
:thinking: do we really want this

**Comment by Ovyerus** [comment]
Added in 60329f1
