### ISSUE TITLE
Bot Crashes when Music Queue's Size reaches 3

### ISSUE THREAD

**Issue by sr229** [awau/Clara#39]
Known to crash when you queue a song and it reaches position 3

No Debug info or crash log yet

UPDATE: also happens when Bot is about to play the 3rd song, seems to be the ctx.msg.author returning undefined again 😖 

UPDATE2: suspected this loop is causing it 
![image](https://cloud.githubusercontent.com/assets/14976516/23065993/363a917c-f553-11e6-9105-eafaa4c82e2d.png)

**Comment by Ovyerus** [comment]
Fixed.
