### ISSUE TITLE
SoundCloud, Discord CDN and Other Sources for Music Support

### ISSUE THREAD

**Issue by sr229** [awau/Clara#46]
Long-Requested Feature since Pre-test Alpha

**Comment by sr229** [comment]
I don't think we can support that right now due to the complexity of the such work but that may be on Backlog.


As long as there's only two twats working on Clara, this may never happen.

**Comment by Ovyerus** [comment]
As long as I can get access to said stream through some sort of API or module, implementation would be possible and somewhat easy, however I have concern for the possibility of them being unstable and people queueing them and then forgetting and leaving, while the bot is using memory and CPU for no reason.

**Comment by HexadecimalPython** [comment]
A checks for if there are users in the voice channel and is not deafened should do the job for that.
If there are no voice members it pauses the receiving of the stream (which should make it pickup to where the stream is upon resuming) and after a set amount of minutes or hours it auto disconnects.

**Comment by sr229** [comment]
I bealieve youtube-dl supports SC and other sauces rightout the box, we should use that since it uses a similar syntax to ytdl-core

**Comment by Ovyerus** [comment]
SoundCloud and Clyp support has been added in 47e4dd077e584386232570ae93e8ceddc1cf957b - 00abc46170acc3bcc49c9458a78b19747e172b31

**Comment by Ovyerus** [comment]
Twitch stream support added in 8843ee1294c905b73403dfed4f88cd3cbbdcae5c
