### ISSUE TITLE
Music sometimes doesn't register objects into the collections.

### ISSUE THREAD

**Issue by Ovyerus** [awau/Clara#47]
I have noticed during my testing, that occasionally when the bot joins a voice channel, nothing gets added to the appropriate music collections, resulting in the bot thinking that it isn't in a voice channel, and therefore not playing anything.

**Comment by sr229** [comment]
Somehow this issue is related to #39 during the Pre-Alpha Testing.

**Comment by Ovyerus** [comment]
Fixed in latest changes.
