### ISSUE TITLE
Moderation Extension: Clean Command

### ISSUE THREAD

**Issue by sr229** [awau/Clara#48]
yeah, sometimes we need a little bit of cleaning.

#### Proposed
- [x] Basic Functionality
- [x] pass args on which to clean (Guild Admin only command, for example ``k.clean bots`` would clean anything bots, additing an additional integer for example ``k.clean bots 10`` would clean the most recent 10 messages from bots)

**Comment by Ovyerus** [comment]
Name it `purge` or `prune` because I plan on implementing bot only purging and calling it `clean`. Also you can pull and adapt this from knife-bot if you wish.

**Comment by sr229** [comment]
that would require tedious amounts of refactoring though

**Comment by sr229** [comment]
Milestone Done. Closing
