### ISSUE TITLE
Music cannot play longer than 2hrs music

### ISSUE THREAD

**Issue by sr229** [awau/Clara#52]
most common error to see is ``stdout maxBuffer Reached``

**Comment by Ovyerus** [comment]
Not much I can do about `stdout maxBuffer Reached` and my code is so much of a mess that I'll most likely need to rewrite it.

**Comment by Ovyerus** [comment]
`stdout maxBuffer reached` should now be fixed with the removal of using youtube-dl. 2 hour videos+ have not been tested
