### ISSUE TITLE
[Confirmed] ReThink does not create a new pool at localhost

### ISSUE THREAD

**Issue by sr229** [awau/Clara#67]

**Comment by Ovyerus** [comment]
Production is running with default connection settings to localhost. Invalid

**Comment by Ovyerus** [comment]
Needs steps to reproduce.

**Comment by sr229** [comment]
Can be easily reproduced with a copy of Clara in a machine without RethinkDB
would crash the bot with this on stacktrace
```prolog
info Loaded 44 commands.
error Experienced error while loading commands:
ReqlDriverError: None of the pools have an opened connection and failed to open a new one.```

**Comment by Ovyerus** [comment]
If the machine does not have Rethink, then that is an end user fault and not a problem with our code
