### ISSUE TITLE
Fallback to Volatile Eris Collection if Rethink is not present.

### ISSUE THREAD

**Issue by sr229** [awau/Clara#68]
although it has some caveats, it should work for selfhosts who can't even get Rethink working

**Comment by sr229** [comment]
One perfect example of this are Heroku deploys

**Comment by Ovyerus** [comment]
After music.

**Comment by Ovyerus** [comment]
Due to the reliance on functions which are only available in RethinkDB, this may not be possible (and storing data that's meant to be preservered, in collections is kinda pointless).

**Comment by sr229** [comment]
Closing since we'll phase out Rethink
