### ISSUE TITLE
Minor memory leak

### ISSUE THREAD

**Issue by Ovyerus** [awau/Clara#69]
Appears to be some minor memory leak somewhere, as memory usage grows from 70mb to 100mb over the course of 2 days. May be related to music however memory usage stays the same even with no queues and music unloaded. Will investigate further.

**Comment by sr229** [comment]
Related to #63

**Comment by Ovyerus** [comment]
Most likely just caching

**Comment by Ovyerus** [comment]
Traced down to being caching, as we cache both guild and user data. This has started happening on Knife Bot v2 and there isn't really much we can do other than moving database to one for caching such as Redis.

**Comment by sr229** [comment]
Reopnening since it's now part of task for 0.4.0 Ravishing Riko to switch to Redis
