### ISSUE TITLE
0.3.0 Road Map

### ISSUE THREAD

**Issue by sr229** [awau/Clara#71]
This would be our Milestone tracker so we know what the fuck are we doing.

- [x] Music Improvements
- [x] Chatbot Improvements. Context Aware chains integration or similar.
- [x] Fix performance issues, particularly the memory leak

Add more if needed.

**Comment by H3xadecimal** [comment]
Fix the fucking memory leak.

**Comment by sr229** [comment]
update: think we fixed some parts of the bot that causes some of the leaks. We believe the crux of this is the caching system.
