### ISSUE TITLE
Extend Moderation

### ISSUE THREAD

**Issue by sr229** [awau/Clara#72]
### TODO : 
- [x] add the ability to ban/kick users by just typing username/UserID
- [x] Unban

**Comment by Ovyerus** [comment]
I'm gonna leave this until 0.4 ~~so I can be lazy and just copy/paste code from Knife Bot~~ so its easier to manage and so that I can easily port Knife Bot's lookups module.

**Comment by sr229** [comment]
Jumped to 0.4.0

**Comment by Ovyerus** [comment]
Done in 7772054
