### ISSUE TITLE
[x-BugReport] Soundcloud Playlist bug 

### ISSUE THREAD

**Issue by sr229** [awau/Clara#83]
![image](https://user-images.githubusercontent.com/14976516/28555594-8d801478-7133-11e7-983b-9f6f3a43d703.png)

**Comment by sr229** [comment]
@Ovyerus you might look into this one fter 0.4.0 is sufficiently fixed core-wise

**Comment by Ovyerus** [comment]
Fixed by accident in b71286071f7fd568b9c168050033c27cfb4631c4 (I think)

**Comment by sr229** [comment]
not marked as fixed until it has been ported to ``lts``

**Comment by Ovyerus** [comment]
🅱

**Comment by sr229** [comment]
:b:fixed
