### ISSUE TITLE
White House Petition API integration

### ISSUE THREAD

**Issue by sr229** [awau/Clara#86]
idk for memes

blame trump

[API Reference](https://petitions.whitehouse.gov/developers)

**Comment by Greek** [comment]
why
is
this
added
lol

**Comment by Greek** [comment]
u meme

**Comment by Ovyerus** [comment]
but y

**Comment by sr229** [comment]
im bored ok

**Comment by Greek** [comment]
old meme
closing
not

**Comment by sr229** [comment]
Trump is gya
