### ISSUE TITLE
Python-based Music Handler

### ISSUE THREAD

**Issue by sr229** [awau/Clara#88]
After too many frustrations over the Music module which is currently in pure JavaScript, it is evident we had to use another language for Music. Python was foresaw as it had more better performance at music-related requests.

### TODO
- [ ] a purely python music handler.
- [ ] An Abstraction or "Bridge" for the handler to interact with.

**Comment by Ovyerus** [comment]
rip my efforts

**Comment by sr229** [comment]
THose who volunteered during dicussion are added to assignees (except for ovy)

**Comment by Ovyerus** [comment]
What clear advantages does this have over a native music system?

**Comment by sr229** [comment]
probably more optimized than our current one @Ovyerus

**Comment by Ovyerus** [comment]
I don't really think this is a good idea. Node has been shown to be faster than Python. Also I'm not sure how'd it be handled ~~inb4 IPC or RPC~~, and it would just be easier to optimise our current implementation.

**Comment by Martmists-GH** [comment]
Node is faster, but generally requires better hardware to work properly, which is why I'm assuming we'll want to use Python.

**Comment by Ovyerus** [comment]
Yeah, but we're already using Node to begin with.

**Comment by sr229** [comment]
Reason behind this is the handler we currently have is very unoptimized and buggy so its better we use a host lang like Py and provide a IPC bridge instead

**Comment by Ovyerus** [comment]
Fixing and optimisation exists /shrug

**Comment by sr229** [comment]
@Ovyerus it's stil lunoptimized :v

**Comment by Ovyerus** [comment]
Time™

**Comment by Ovyerus** [comment]
Closing due to negotations
