### ISSUE TITLE
Use async on some commands

### ISSUE THREAD

**Issue by sr229** [awau/Clara#91]
since we'll be supporting async for 0.4.0, we should make a list of those commands that need to use async explicitly

### Checklist

Add the commands that need to use async explicitly here

**Comment by Ovyerus** [comment]
Commands needing async:
 - all of them


:^)

**Comment by H3xadecimal** [comment]
Correction: Use async for everything.

**Comment by Greek** [comment]
async is the future

**Comment by Ovyerus** [comment]
Done majorly in 73ec538
